const items=[
  {
    id:'001',
    image:'images/1.jpg',
    company:'Carton London',
    item_name:'Rhodium-Plated CZ Floral Studs',
    original_price:1045,
    current_price:606,
    discount_percentage:'42',
    rating:{
      stars:4.5,
      count:1400,
    },
  },
  {
    id:'002',
    image:'images/2.jpg',
    company:'Forever Glam',
    item_name:'Halter Neck Swimmimg Dress',
    original_price:1225,
    current_price:565,
    discount_percentage:'34',
    rating:{
      stars:3.5,
      count:2400,
    },
  },
  {
    id:'003',
    image:'images/3.jpg',
    company:'Louis Vuiton',
    item_name:'Red Floral Skirt',
    original_price:625,
    current_price:565,
    discount_percentage:'14',
    rating:{
      stars:4.5,
      count:200,
    },
  },
  {
    id:'004',
    image:'images/4.jpg',
    company:'Adidas',
    item_name:'Team India Jersey',
    original_price:925,
    current_price:565,
    discount_percentage:'39',
    rating:{
      stars:5.0,
      count:24000,
    },
  },
  {
    id:'005',
    image:'images/5.jpg',
    company:'Roadster',
    item_name:'Solid Black T-Shirt',
    original_price:925,
    current_price:595,
    discount_percentage:'64',
    rating:{
      stars:2.5,
      count:23300,
    },
  },
  {
    id:'006',
    image:'images/6.jpg',
    company:'Nike',
    item_name:'White Sports Shoes',
    original_price:6625,
    current_price:5605,
    discount_percentage:'24',
    rating:{
      stars:4.5,
      count:7400,
    },
  },
  {
    id:'007',
    image:'images/7.jpg',
    company:'Jockey',
    item_name:'Olive Green Cotton Shorts',
    original_price:625,
    current_price:565,
    discount_percentage:'10',
    rating:{
      stars:3.5,
      count:2400,
    },
  },
  {
    id:'008',
    image:'images/8.jpg',
    company:'Nivea',
    item_name:'Perfume for Men',
    original_price:325,
    current_price:225,
    discount_percentage:'34',
    rating:{
      stars:4.5,
      count:200,
    },
  },
 
];